### ISSUE TITLE
Can't find allure commandline in Pipeline Jenkinsfile

### ISSUE THREAD

**Issue by tegarraharditya** [allure-framework/allure1#950] opened 2017-04-05 10:29 UTC
Can't find allure commandline when using pipeline (Jenkinsfile), if we are using freestyle , (Post Build Step) it is no issue.

**Comment by baev** [comment] 2017-04-14 11:45
@eroshenkoam am I right that the issue is fixed in 2.15?

**Comment by 9ah** [comment] 2017-05-03 08:33
Hi, i am using the version 2.15 and I experience the same issue too - Can't find allure commandline <null>

**Comment by baev** [comment] 2017-05-10 13:46
Could you please move the issue to https://github.com/jenkinsci/allure-plugin/issues

**Closed by baev** 2017-05-10 13:46 UTC
