### ISSUE TITLE
Strange behavior in description block

### ISSUE THREAD

**Issue by DudaGod** [allure-framework/allure1#912] opened 2017-02-02 18:51 UTC
Hello guys.

I have a problem with description block. I generate description text in markdown and usually it is a list of some actions. The problem is that the description text is hidden when I opening report and in right corner of description block appears a link with "show full..." text. So every time when I look through tests I should click on this link - it is really annoying.

How it looks after open test report - [img-link-1](https://yadi.sk/i/F02S5Hga3CXesf)
How it looks when I click on "show full..." link - [img-link-2](https://yadi.sk/i/FboheODM3CXetA)
And how it looks when I don't use lists in markdown - [img-link-3](https://yadi.sk/i/ShQC0x2I3CXeu7)

My xml report
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:test-suite xmlns:ns2="urn:model.allure.qatools.yandex.ru" start="1486043805711" stop="1486043821734">
	<name>Suite Title</name>
	<title>Suite Title</title>
	<description type="markdown">
* do: test &apos;value&apos;
* assert: **strong**
* do: ~~delete~~
* do: ***test***
* assert: __italic__
* do: value1
* assert: res2</description>
	<test-cases>
		<test-case start="1486043805713" stop="1486043821725" status="passed">
			<name>Test Title</name>
			<title>Test Title</title>
			<labels>
			</labels>
			<parameters>
				<parameter kind="environment-variable" name="url" value="test-url"/>
				<parameter kind="environment-variable" name="browser" value="chrome-phone"/>
			</parameters>
			<steps>
			</steps>
			<attachments>
			</attachments>
		</test-case>
	</test-cases>
</ns2:test-suite>
```

This is quite strange. I spent a lot of time to find code that responsible for that behavior.
Can you help me to figure out how it works?

**Comment by baev** [comment] 2017-03-01 14:29
@DudaGod sorry for the delay. The issue is fixed in 1.5 and 2.0 as well

## 1.5
<img width="328" alt="screen shot 2017-03-01 at 17 27 58" src="https://cloud.githubusercontent.com/assets/2149631/23463974/7c90c038-fea4-11e6-95d7-9a0582d2e8de.png">

## 2.0
<img width="332" alt="screen shot 2017-03-01 at 17 28 05" src="https://cloud.githubusercontent.com/assets/2149631/23463978/806026fe-fea4-11e6-974f-5b7c5ce50ea6.png">

**Closed by baev** 2017-03-01 14:29 UTC
