### ISSUE TITLE
java.util.ConcurrentModificationException on multithreaded TestNG tests

### ISSUE THREAD

**Issue by SSgtMendel** [allure-framework/allure1#906] opened 2017-01-31 06:53 UTC
Hi, 

I'm getting the following error occasionally when i run tests multi-threaded via TestNG xml. It happens when the tests try to write to the report at the same time i suppose.

    @Step(value = "{0}")
    protected void writeToReport(String message) {
    }

java.util.ConcurrentModificationException
	at java.util.Hashtable$Enumerator.next(Hashtable.java:1367)
	at java.util.Hashtable.putAll(Hashtable.java:522)
	at ru.yandex.qatools.properties.providers.DefaultPropertyProvider.provide(DefaultPropertyProvider.java:31)
	at ru.yandex.qatools.properties.PropertyLoader.populate(PropertyLoader.java:28)
	at ru.yandex.qatools.properties.PropertyLoader.populate(PropertyLoader.java:23)
	at ru.yandex.qatools.allure.config.AllureConfig.<init>(AllureConfig.java:79)
	at ru.yandex.qatools.allure.config.AllureConfig.newInstance(AllureConfig.java:83)
	at ru.yandex.qatools.allure.aspects.AllureAspectUtils.getTitle(AllureAspectUtils.java:68)
	at ru.yandex.qatools.allure.aspects.AllureStepsAspects.createTitle(AllureStepsAspects.java:69)
	at ru.yandex.qatools.allure.aspects.AllureStepsAspects.stepStart(AllureStepsAspects.java:41)
	

From my pom:
        <aspectj.version>1.8.9</aspectj.version>
        <allure.version>1.5.0</allure.version>
        <allure.plugin.version>2.5</allure.plugin.version>
        <testng.version>6.10</testng.version>

**Comment by SSgtMendel** [comment] 2017-01-31 06:55
![image](https://cloud.githubusercontent.com/assets/11193662/22455094/06032992-e793-11e6-8891-47e695ba5346.png)

**Comment by SSgtMendel** [comment] 2017-01-31 08:04
This might not be it but after i made the above-mentioned method synchronized issue seems to have stopped reproducing; Will update if it happens again

@Step(value = "{0}")
protected void writeToReport(String message) {
}

@Step(value = "{0}")
protected synchronized void writeToReport(String message) {
}

**Comment by SSgtMendel** [comment] 2017-01-31 11:20
Still reproduces...

**Comment by mdfaller** [comment] 2017-02-09 21:49
I'm seeing this under similar circumstances -- multi-threaded TestNG xml suites.

> java.util.ConcurrentModificationException
at java.util.Hashtable$Enumerator.next(Unknown Source)
at java.util.Hashtable.putAll(Unknown Source)
at ru.yandex.qatools.properties.providers.DefaultPropertyProvider.provide(DefaultPropertyProvider.java:31)
at ru.yandex.qatools.properties.PropertyLoader.populate(PropertyLoader.java:28)
at ru.yandex.qatools.properties.PropertyLoader.populate(PropertyLoader.java:23)
at ru.yandex.qatools.allure.config.AllureConfig.<init>(AllureConfig.java:79)
at ru.yandex.qatools.allure.config.AllureConfig.newInstance(AllureConfig.java:83)
at ru.yandex.qatools.allure.testng.AllureTestListener.onTestStart(AllureTestListener.java:155)
at org.testng.internal.Invoker.runTestListeners(Invoker.java:1695)
at org.testng.internal.Invoker.runTestListeners(Invoker.java:1670)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:615)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)

allure 1.5.0
aspectj 1.8.3
testng 6.9.9

**Comment by baev** [comment] 2017-02-09 22:16
@mdfaller @SSgtMendel It would be so nice if some of you guys will create a sample project to reproduce the problem

**Comment by SSgtMendel** [comment] 2017-02-10 14:25
Will create a simple maven project beginning of next week to reproduce this.

**Comment by mdfaller** [comment] 2017-02-10 15:07
It looks like we set a system property in a @BeforeClass method. Allure sets system properties during the onTestStart() routine (DefaultPropertyProvider.java:31). That's probably where we're stepping on each other.

**Comment by baev** [comment] 2017-02-10 15:08
BTW is that issue fixed in `1.5.1`?

**Comment by SSgtMendel** [comment] 2017-02-13 08:33
For the life of me I could not reproduce it in a simple project...i'll try and change the version to 1.5.1 and see if it occurs again

**Comment by SSgtMendel** [comment] 2017-02-13 14:59
Seems to have gone away with version 1.5.1...will post if i see it again

**Comment by baev** [comment] 2017-02-13 15:01
@SSgtMendel ok. 

BTW Feel free to reopen

**Closed by baev** 2017-02-13 15:01 UTC
Labels: review
