### ISSUE TITLE
Problem with repository address -

### ISSUE THREAD

**Issue by bruuhnicole** [allure-framework/allure1#856] opened 2016-09-12 18:07 UTC
When I execut site command on cmd, the issue below appear:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.3:site (default-site) on project allure-juni
t-example: SiteToolException: The site descriptor cannot be resolved from the repository: ArtifactResolutionException: U
nable to locate site descriptor: Could not transfer artifact ru.yandex.qatools.allure:allure-examples-parent:xml:site_en
:1.0 ....

Is repository updated?

**Comment by vania-pooh** [comment] 2016-09-13 08:34
Summon @baev.

**Comment by baev** [comment] 2016-09-13 10:02
@bruuhnicole hi!

The project has been updated.

**Comment by bruuhnicole** [comment] 2016-09-13 12:20
Hello @baev! Thanks for updating, but the problem persist. Maven is trying to download the "io/qameta/opensource-parent/1.3/opensource-parent-1.3-site_en.xml" from my internal repository. What 's your repository configuration? Is this?

<repository>
	<id>snapshots-repo</id>  
	<name>Snapshots Repo</name>         
        <url>https://oss.sonatype.org/content/repositories/snapshots</url> 
	<releases>           
            <enabled>false</enabled>           
        </releases>           
        <snapshots>           
            <enabled>true</enabled>           
        </snapshots>   
</repository>

**Comment by baev** [comment] 2016-09-13 13:24
I could not reproduce the problem. Everything works fine for me (I even tried maven-site-plugin 3.3 and the latest 3.5.1). I have default `settings.xml` and Maven version 3.3.9

**Comment by baev** [comment] 2016-09-13 16:57
@bruuhnicole I don't know why you have such problems with site goal; you can simply use `allure-maven-plugin` in plugins section:

```xml
<plugin>
    <groupId>ru.yandex.qatools.allure</groupId>
    <artifactId>allure-maven-plugin</artifactId>
    <version>2.5</version>
</plugin>
``xml

and goal `allure:report` to generate the report.

**Comment by bruuhnicole** [comment] 2016-09-15 17:18
All right @baev, I'll try to do this. Thanks!

**Comment by sseliverstov** [comment] 2017-01-24 20:38
@bruuhnicole, can i close this issue?

**Comment by bruuhnicole** [comment] 2017-01-25 15:13
@sseliverstov sure! Thanks.

**Closed** 2017-01-25 17:46 UTC
Labels: question
