### ISSUE TITLE
Class name is added into suite name in allure report.

### ISSUE THREAD

**Issue by ivan-baranovski-intellectsoft** [allure-framework/allure1#941] opened 2017-03-07 12:28 UTC
I run api tests using java+rest-assured+testNg+Maven+Allure. I am new in Allure report.
I have testNg xml file that contains some suites. In result we have all suites in {suite_name : test_class_name} format. Why does this happen? Please, somebody help.
![8](https://cloud.githubusercontent.com/assets/12170395/23656376/8a55cbb4-034a-11e7-977b-96616a4bb9d4.png)

**Comment by ivan-baranovski-intellectsoft** [comment] 2017-03-09 09:23
It was fixed in allure2 version. But this is only beta version.

**Comment by baev** [comment] 2017-03-11 10:46
The problem is that Allure 1 doesn't support nested suites, so we need to store the information about suite/test/class like this. I don't think this gonna be fixed in allure1

And you right, the issue is already fixed in Allure 2

**Closed by baev** 2017-03-11 10:46 UTC
